<?php
/**
 * Styles for the footer newsletter signup form (native HTML widget markup
 * generated by the footer rebuild script — matches the Origins reference:
 * outlined input + outlined all-caps submit button on the dark footer bg).
 *
 * CSS moved to: wp-content/themes/hello-elementor-child/assets/css/amq-footer-signup.css
 */

if (!defined('ABSPATH')) exit;
